const navItems = [
  ["dashboard","⌂","Command Center"], ["workflow","◇","Client Workflow","24"], ["clients","○","Clients"],
  ["forms","□","Forms & Intake"], ["portal","↗","Client Portal"], ["communications","✉","Communications","7"],
  ["documents","▱","Documents"], ["payments","$","Payments"], ["team","♙","Team"], ["reports","⌁","Reports"], ["settings","⚙","Settings"]
];

window.STP_APP_LOADED = true;

const stages = [
  ["new","New Lead","#8f9b96"],["intake","Intake Sent","#8b6faa"],["intake-complete","Intake Completed","#6c65a5"],
  ["documents","Documents Needed","#a36f4a"],["ready","Ready for Preparation","#4f769d"],["preparation","In Preparation","#cb8503"],
  ["review","Under Review","#347760"],["corrections","Corrections Needed","#bd5c4f"],["payment","Awaiting Payment","#b9842d"],
  ["signature","Awaiting Signature","#9b6b30"],["file","Ready to File","#378277"],["filed","Filed","#287765"],
  ["accepted","Accepted","#168665"],["rejected","Rejected","#b5344b"],["completed","Completed","#315c52"],["hold","On Hold","#776b72"]
];

const originalClients = [
  {id:1,name:"Ashley Williams",email:"ashley.williams@example.com",phone:"(404) 555-0182",type:"Individual · 1040",stage:"documents",assignee:"Myah Turner",balance:275,activity:"Today",priority:true,tags:["W-2 missing"]},
  {id:2,name:"Danielle Carter",email:"danielle.carter@example.com",phone:"(404) 555-0124",type:"Business · Schedule C",stage:"preparation",assignee:"Myah Turner",balance:0,activity:"12 min ago",tags:["Schedule C"]},
  {id:3,name:"Marcus Johnson",email:"marcus.johnson@example.com",phone:"(678) 555-0144",type:"Individual · 1040",stage:"review",assignee:"Danielle Reed",balance:0,activity:"28 min ago",tags:["Review"]},
  {id:4,name:"Keisha Brown",email:"keisha.brown@example.com",phone:"(770) 555-0129",type:"Individual · 1040",stage:"intake",assignee:"Kiara Banks",balance:150,activity:"2 days",priority:true,tags:["Follow-up"]},
  {id:5,name:"Terrence Moore",email:"terrence.moore@example.com",phone:"(404) 555-0166",type:"Business · Schedule C",stage:"new",assignee:"Myah Turner",balance:0,activity:"35 min ago",tags:["Web lead"]},
  {id:6,name:"Tasha Green",email:"tasha.green@example.com",phone:"(404) 555-0198",type:"Business · 1120-S",stage:"documents",assignee:"Danielle Reed",balance:450,activity:"4 hours",tags:["Bank statements"]},
  {id:7,name:"Nicole Harris",email:"nicole.harris@example.com",phone:"(678) 555-0115",type:"Individual · 1040",stage:"intake-complete",assignee:"Kiara Banks",balance:0,activity:"Today",tags:["Ready"]},
  {id:8,name:"James Robinson",email:"james.robinson@example.com",phone:"(770) 555-0162",type:"Individual · 1040",stage:"corrections",assignee:"Myah Turner",balance:0,activity:"2 hours",priority:true,tags:["Correction"]},
  {id:9,name:"Brittany Ellis",email:"brittany.ellis@example.com",phone:"(404) 555-0171",type:"Individual · 1040",stage:"ready",assignee:"Danielle Reed",balance:0,activity:"1 day",tags:["File complete"]},
  {id:10,name:"Andre Walker",email:"andre.walker@example.com",phone:"(678) 555-0138",type:"Business · Schedule C",stage:"preparation",assignee:"Kiara Banks",balance:325,activity:"3 days",tags:["Bookkeeping"]},
  {id:11,name:"Calvin Brooks",email:"calvin.brooks@example.com",phone:"(770) 555-0187",type:"Individual · 1040",stage:"payment",assignee:"Kiara Banks",balance:575,activity:"1 day",priority:true,tags:["Balance due"]},
  {id:12,name:"Jasmine Clark",email:"jasmine.clark@example.com",phone:"(404) 555-0149",type:"Business · Schedule C",stage:"signature",assignee:"Myah Turner",balance:0,activity:"4 hours",tags:["8879 sent"]},
  {id:13,name:"Robert Lewis",email:"robert.lewis@example.com",phone:"(678) 555-0153",type:"Individual · 1040",stage:"file",assignee:"Danielle Reed",balance:0,activity:"25 min ago",tags:["Ready"]},
  {id:14,name:"Candace Hall",email:"candace.hall@example.com",phone:"(770) 555-0158",type:"Individual · 1040",stage:"filed",assignee:"Kiara Banks",balance:0,activity:"8 hours",tags:["IRS pending"]},
  {id:15,name:"Derrick White",email:"derrick.white@example.com",phone:"(404) 555-0135",type:"Individual · 1040",stage:"accepted",assignee:"Myah Turner",balance:0,activity:"Today",tags:["Federal accepted"]},
  {id:16,name:"Pamela Scott",email:"pamela.scott@example.com",phone:"(678) 555-0176",type:"Business · Schedule C",stage:"rejected",assignee:"Danielle Reed",balance:0,activity:"43 min ago",priority:true,tags:["IND-031-04"]},
  {id:17,name:"Courtney Young",email:"courtney.young@example.com",phone:"(770) 555-0194",type:"Individual · 1040",stage:"completed",assignee:"Kiara Banks",balance:0,activity:"Yesterday",tags:["Final copy sent"]},
  {id:18,name:"Avery Mitchell",email:"avery.mitchell@example.com",phone:"(404) 555-0119",type:"Individual · 1040",stage:"hold",assignee:"Myah Turner",balance:275,activity:"7 days",priority:true,tags:["No response"]}
];

let clients = loadClients();
let currentView = "dashboard";
let workflowMode = "board";
let activeThread = 0;
let appInitialized = false;

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const initials = (name) => name.split(" ").map(part => part[0]).join("").slice(0,2).toUpperCase();
const stageLabel = (id) => stages.find(stage => stage[0] === id)?.[1] || id;
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);

function cloneDefaults(){ return JSON.parse(JSON.stringify(originalClients)); }
function loadClients(){ try { return JSON.parse(localStorage.getItem("stp-static-clients")) || cloneDefaults(); } catch { return cloneDefaults(); } }
function saveClients(){ try { localStorage.setItem("stp-static-clients", JSON.stringify(clients)); } catch { /* The demo still works when browser storage is unavailable. */ } }
function toast(message){ $("#toastText").textContent=message; $("#toast").classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>$("#toast").classList.remove("show"),2500); }

function renderNav(){
  $("#sideNav").innerHTML=navItems.map(([id,icon,label,badge])=>`<button data-view="${id}" class="${id===currentView?"active":""}"><span class="nav-icon">${icon}</span><span>${label}</span>${badge?`<b>${badge}</b>`:""}</button>`).join("");
}

function navigate(view){ currentView=view; renderNav(); renderView(); $("#sidebar").classList.remove("open"); $("#sidebarScrim").classList.remove("open"); window.scrollTo({top:0,behavior:"smooth"}); }
function heading(eyebrow,title,copy,actions=""){ return `<section class="module-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${copy}</p></div><div class="heading-actions">${actions}</div></section>`; }
function panelHeader(eyebrow,title,action="View all"){ return `<div class="panel-header"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div><button data-toast="${title} opened.">${action} →</button></div>`; }
function metric(label,value,note,accent=""){ return `<article class="metric-card ${accent}"><div><span>${label}</span><strong>${value}</strong><small>${note}</small></div><div class="mini-trend"><i></i><i></i><i></i><i></i><i></i></div></article>`; }

function dashboard(){
  const date=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"});
  const bars=[48,56,44,68,61,77,71,88,82,94,86,100]; const months=["SEP","OCT","NOV","DEC","JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG"];
  return `<div class="page">
    <section class="page-heading"><div><p class="eyebrow">${date.toUpperCase()}</p><h1>Good morning, <em>Tax Pro.</em></h1><p>Here is what requires your attention today.</p></div><div class="heading-actions"><button class="button secondary" data-export="report">⇩ Export report</button><button class="button primary" data-add-client>＋ Add client</button></div></section>
    <section class="attention-banner"><div class="attention-icon">!</div><div><strong>12 items need your attention</strong><p>3 rejected returns, 5 missing documents, and 4 overdue tasks</p></div><button data-view="workflow">Review priorities →</button></section>
    <section class="metric-grid">${metric("Active clients","184","+18 this month")}${metric("Returns in progress","126","68% of active files","gold")}${metric("Need attention","12","3 marked urgent","rose")}${metric("Revenue collected","$84.6K","+12.4% this season")}</section>
    <section class="dashboard-grid top"><article class="panel">${panelHeader("OFFICE PERFORMANCE","Revenue overview","View report")}<div class="revenue-summary"><div><span>Collected this season</span><strong>$84,620</strong><small>↑ 12.4% from last season</small></div></div><div class="bar-chart">${bars.map((h,i)=>`<div class="bar-group"><i style="height:${Math.max(15,h-22)}%"></i><b style="height:${h}%"></b><span>${months[i]}</span></div>`).join("")}</div></article>
    <article class="panel">${panelHeader("LIVE SNAPSHOT","Return status","View workflow")}<div class="donut-row"><div class="donut"><div><strong>184</strong><span>ACTIVE</span></div></div><div class="status-list">${[["#cb8503","In preparation","46"],["#1f6b52","Under review","31"],["#7b64a8","Awaiting client","52"],["#d05d5d","Needs correction","12"],["#d9dedb","Other stages","43"]].map(x=>`<div><span><i style="background:${x[0]}"></i>${x[1]}</span><b>${x[2]}</b></div>`).join("")}</div></div></article></section>
    <section class="dashboard-grid bottom"><article class="panel">${panelHeader("ACTION REQUIRED","Priority queue")}<div class="priority-list">${[["Pamela Scott","Federal return rejected","Rejected"],["Ashley Williams","W-2 and photo ID missing","Documents"],["Calvin Brooks","$575 balance outstanding","Payment"],["Jasmine Clark","Form 8879 awaiting signature","Signature"]].map(x=>`<button data-client-name="${x[0]}"><span class="dot">!</span><span><strong>${x[0]}</strong><small>${x[1]}</small></span><b>${x[2]}</b></button>`).join("")}</div></article><article class="panel">${panelHeader("HAPPENING NOW","Recent activity")}<div class="activity-list">${[["DS","Danielle submitted her intake","12 minutes ago"],["MT","Return moved to quality review","28 minutes ago"],["PS","IRS rejection received","43 minutes ago"],["CB","Payment reminder delivered","1 hour ago"]].map(x=>`<div><span class="activity-avatar">${x[0]}</span><p><strong>${x[1]}</strong><small>${x[2]}</small></p><i></i></div>`).join("")}</div></article></section>
    <section class="quick-actions"><div><p class="eyebrow">QUICK ACTIONS</p><h2>Keep the office moving</h2></div><div><button data-add-client><span>＋</span>Add a client</button><button data-view="communications"><span>✉</span>Send a message</button><button data-view="documents"><span>⇧</span>Request documents</button><button data-view="payments"><span>$</span>Record payment</button></div></section>
  </div>`;
}

function workflow(){
  const outstanding=clients.reduce((sum,c)=>sum+c.balance,0).toLocaleString();
  const toolbar=`<div class="workflow-toolbar"><div class="view-switch"><button data-mode="board" class="${workflowMode==="board"?"active":""}">Board</button><button data-mode="list" class="${workflowMode==="list"?"active":""}">List</button></div><div class="module-search">⌕ <input id="workflowSearch" placeholder="Search workflow"></div><div class="workflow-stats"><span><b>${clients.length}</b> demo files</span><span><b>${clients.filter(c=>c.priority).length}</b> need attention</span><span><b>$${outstanding}</b> outstanding</span></div></div>`;
  return `<div class="page">${heading("TAX OFFICE OPERATIONS","Client Workflow","Move every return through a clear, dependable process.",'<button class="button secondary">☷ Filter</button><button class="button primary" data-add-client>＋ Add client</button>')}${toolbar}<div id="workflowArea">${workflowMode==="board"?kanban():clientTable(clients)}</div></div>`;
}
function kanban(list=clients){ return `<div class="kanban-board">${stages.map(([id,label,color])=>{const items=list.filter(c=>c.stage===id);return `<section class="kanban-column" data-stage="${id}"><header style="--stage:${color}"><i></i><strong>${label}</strong><b>${items.length}</b></header><div class="kanban-stack">${items.map(clientCard).join("")}</div></section>`}).join("")}</div>`; }
function clientCard(c){ return `<button class="kanban-card" draggable="true" data-client-id="${c.id}"><div><strong>${escapeHtml(c.name)}</strong>${c.priority?"<b>!</b>":""}</div><small>${escapeHtml(c.type)}</small><em>${escapeHtml(c.tags[0])}</em><footer><span>${initials(c.name)} · ${c.assignee.split(" ")[0]}</span><b>${c.balance?`$${c.balance}`:"Paid"}</b></footer></button>`; }

function clientsPage(){ return `<div class="page">${heading("CLIENT MANAGEMENT","Clients","Every taxpayer, business, and return in one organized workspace.",'<button class="button secondary" data-export="clients">⇩ Export CSV</button><button class="button primary" data-add-client>＋ Add client</button>')}<section class="module-metrics">${metric("TOTAL CLIENTS","246","28 added this month")}${metric("ACTIVE RETURNS","184","74.8% of records")}${metric("RETURNING CLIENTS","78%","Up 6% this season")}${metric("NEEDS FOLLOW-UP",String(clients.filter(c=>c.priority).length),"Priority demo records")}</section><section class="table-panel"><div class="table-toolbar"><div class="module-search">⌕ <input id="clientSearch" placeholder="Search name or email"></div><div class="filter-chips"><button class="active">All clients</button><button>Individual</button><button>Business</button><button>Needs attention</button></div></div><div id="clientTableWrap">${clientTable(clients)}</div></section></div>`; }
function clientTable(list){ return `<div class="table-scroll"><table class="data-table"><thead><tr><th>CLIENT</th><th>RETURN TYPE</th><th>WORKFLOW STATUS</th><th>ASSIGNED TO</th><th>BALANCE</th><th>LAST ACTIVITY</th></tr></thead><tbody>${list.map(c=>`<tr data-client-id="${c.id}"><td><div class="client-cell"><span>${initials(c.name)}</span><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.email)}</small></div></div></td><td>${escapeHtml(c.type)}</td><td><b class="status-chip ${c.priority?"warn":""}">${stageLabel(c.stage)}</b></td><td>${escapeHtml(c.assignee)}</td><td>${c.balance?`$${c.balance}.00`:"Paid"}</td><td>${c.activity}</td></tr>`).join("")}</tbody></table></div>`; }

const formCards=[["New Client Registration","246","82%"],["Individual Tax Intake","184","91%"],["Business Tax Intake","68","76%"],["Document Checklist","219","88%"],["Engagement Agreement","201","94%"],["Bank Enrollment Information","34","71%"]];
function formsPage(){ return `<div class="page">${heading("DIGITAL INTAKE","Forms & Intake","Collect complete, consistent client information before preparation begins.",'<button class="button secondary">Templates</button><button class="button primary" data-toast="Form builder opened in demo mode.">＋ Create form</button>')}<section class="module-metrics">${metric("TOTAL SUBMISSIONS","952","Across active forms")}${metric("AVERAGE COMPLETION","84%","Up 9% this season")}${metric("PENDING REVIEW","17","4 marked urgent")}${metric("SENT THIS WEEK","63","51 completed")}</section><div class="card-grid">${formCards.map((x,i)=>`<article class="feature-card"><div class="number">${String(i+1).padStart(2,"0")}</div><h2>${x[0]}</h2><p>Secure, branded form for your tax-office workflow.</p><div class="facts"><span><b>${x[1]}</b>SUBMISSIONS</span><span><b>${x[2]}</b>COMPLETE</span></div><footer><button data-toast="Demo form link copied.">Copy link</button><button data-toast="${x[0]} preview opened.">Preview →</button></footer></article>`).join("")}</div></div>`; }

function portalPage(){ return `<div class="page">${heading("CLIENT EXPERIENCE","Client Portal Preview","A secure, guided experience that keeps clients informed and organized.",'<button class="button secondary" data-toast="Portal preview link copied.">Copy preview link</button><button class="button primary" data-toast="Viewing the portal as Ashley Williams.">View as client</button>')}<div class="portal-frame"><aside><strong>STP Client Portal</strong>${["Overview","My Return","Documents","Messages","Payments","Appointments"].map((x,i)=>`<button class="${i===0?"active":""}">${x}</button>`).join("")}</aside><main><p class="eyebrow">WELCOME BACK</p><h2>Hello, Ashley.</h2><p>Your tax team is reviewing the documents received for your 2026 return.</p><div class="portal-status"><span>RETURN STATUS</span><strong>Documents needed</strong><div class="status-track"><i class="done"></i><i class="done"></i><i></i><i></i><i></i></div></div><div class="portal-grid"><article><h3>⇧ 2 documents requested</h3><p>W-2 and photo identification</p><button data-toast="Upload is simulated in this demo.">Upload files</button></article><article><h3>✉ New message from your tax team</h3><p>Received today at 8:14 AM</p><button data-toast="Message marked as read.">Read message</button></article><article><h3>$ Balance: $275.00</h3><p>Payment due before filing</p><button data-toast="Payments are not connected in demo mode.">View balance</button></article></div></main></div></div>`; }

function communicationsPage(){ const names=["Ashley Williams","Danielle Carter","Marcus Johnson","Keisha Brown","Terrence Moore"]; return `<div class="page">${heading("UNIFIED INBOX","Communications","Keep every client conversation connected to the correct return.",'<button class="button secondary">Saved replies</button><button class="button primary" data-toast="New message composer opened.">＋ New message</button>')}<div class="inbox"><aside class="thread-list">${names.map((name,i)=>`<button class="${i===activeThread?"active":""}" data-thread="${i}"><span>${initials(name)}</span><div><strong>${name}</strong><small>${i===0?"I’ll upload both documents tonight.":"Thank you for the update!"}</small></div><time>${i<2?"8:14 AM":"Mon"}</time></button>`).join("")}</aside><main class="conversation-pane"><header><div class="client-cell"><span>${initials(names[activeThread])}</span><div><strong>${names[activeThread]}</strong><small>Individual · 1040</small></div></div></header><div class="messages"><p class="message">Hi ${names[activeThread].split(" ")[0]}, we received your intake. We still need the requested documents.</p><p class="message sent">Thank you! I’ll upload everything tonight.</p><p class="message">Perfect. Once those are uploaded, your return will move to preparation.</p></div><div class="composer"><textarea id="messageText" placeholder="Type a demo message…"></textarea><div><button class="button primary" id="sendMessage">Send text</button></div></div></main></div></div>`; }

const documentRows=[["2026 W-2 · Brightline Logistics","Ashley Williams","Income","Needs review","8:42 AM"],["Photo ID · Front and back","Danielle Carter","Identity","Approved","Yesterday"],["January–December statements","Tasha Green","Business","Needs review","Yesterday"],["Form 1099-NEC","Marcus Johnson","Income","Approved","Mon"],["Expense worksheet","Andre Walker","Business","Missing details","Mon"]];
function documentsPage(){ return `<div class="page">${heading("SECURE FILE MANAGEMENT","Documents","Review, organize, and request the records every return needs.",'<button class="button secondary" data-toast="Document request prepared.">Request documents</button><button class="button primary" data-toast="Upload is simulated; no file was transmitted.">⇧ Upload document</button>')}<section class="module-metrics">${metric("TOTAL DOCUMENTS","1,428","2027 tax season")}${metric("NEEDS REVIEW","23","8 uploaded today")}${metric("MISSING","17","Requests outstanding")}${metric("APPROVED TODAY","42","By three reviewers")}</section><section class="table-panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>DOCUMENT</th><th>CLIENT</th><th>CATEGORY</th><th>STATUS</th><th>UPLOADED</th></tr></thead><tbody>${documentRows.map(r=>`<tr data-toast="${r[0]} preview opened."><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td>${r[2]}</td><td><b class="status-chip ${r[3].includes("Needs")||r[3].includes("Missing")?"warn":""}">${r[3]}</b></td><td>${r[4]}</td></tr>`).join("")}</tbody></table></div></section></div>`; }

const payments=[["Calvin Brooks","$575.00","Outstanding","Due today"],["Danielle Carter","$850.00","Paid","Aug 16"],["Tasha Green","$1,250.00","Paid","Aug 15"],["Ashley Williams","$275.00","Outstanding","Aug 14"],["Andre Walker","$325.00","Overdue","Aug 10"]];
function paymentsPage(){ return `<div class="page">${heading("REVENUE MANAGEMENT","Payments","Track collected revenue and follow up on every outstanding balance.",'<button class="button secondary" data-export="payments">⇩ Export transactions</button><button class="button primary" data-toast="Record-payment form opened in demo mode.">＋ Record payment</button>')}<section class="module-metrics">${metric("TOTAL REVENUE","$84,620","2027 tax season")}${metric("COLLECTED","$72,380","85.5% of invoiced")}${metric("OUTSTANDING","$12,240","19 client balances")}${metric("OVERDUE","$3,175","6 require follow-up")}</section><section class="table-panel">${panelHeader("RECENT ACTIVITY","Transactions & balances")}<div class="table-scroll"><table class="data-table"><thead><tr><th>CLIENT</th><th>AMOUNT</th><th>STATUS</th><th>DATE</th><th>METHOD</th></tr></thead><tbody>${payments.map((r,i)=>`<tr data-toast="${r[2]==="Paid"?"Receipt preview opened.":"Reminder prepared—not sent."}"><td><strong>${r[0]}</strong></td><td><strong>${r[1]}</strong></td><td><b class="status-chip ${r[2]!=="Paid"?"warn":""}">${r[2]}</b></td><td>${r[3]}</td><td>${i%2?"Card":"Invoice"}</td></tr>`).join("")}</tbody></table></div></section></div>`; }

function teamPage(){ const team=[["MT","Myah Turner","Senior Tax Preparer",48,19,82],["DR","Danielle Reed","Tax Reviewer",42,16,68],["KB","Kiara Banks","Client Success",51,24,74],["JL","Jordan Lee","Tax Preparer",43,13,51]]; return `<div class="page">${heading("OFFICE COLLABORATION","Team","Balance workloads and keep responsibilities visible across the office.",'<button class="button primary" data-toast="Team invitation prepared in demo mode.">＋ Invite team member</button>')}<div class="team-grid">${team.map(x=>`<article class="team-card"><div class="team-avatar">${x[0]}</div><h2>${x[1]}</h2><p>${x[2]}</p><div class="facts"><span><strong>${x[3]}</strong>ACTIVE FILES</span><span><strong>${x[4]}</strong>OPEN TASKS</span></div><p>Current workload: ${x[5]}%</p><div class="progress"><i style="width:${x[5]}%"></i></div></article>`).join("")}</div></div>`; }

function reportsPage(){ const reports=[["$","Revenue","$84,620","12.4% growth"],["↗","Client Growth","+28","This month"],["◇","Return Status","64%","Season completion"],["!","Outstanding Balances","$12,240","19 clients"],["♙","Team Productivity","91%","Tasks on time"],["%","Lead Conversion","42%","Up 7%"]]; const heights=[25,42,33,56,48,68,62,81,74,92]; return `<div class="page">${heading("OFFICE INTELLIGENCE","Reports","Turn office activity into clear, actionable performance insights.",'<button class="button primary" data-export="report">⇩ Export report</button>')}<div class="report-grid">${reports.map(r=>`<article class="report-card"><div class="report-icon">${r[0]}</div><span>${r[1]}</span><strong>${r[2]}</strong><small>${r[3]}</small><div class="report-spark">${heights.map(h=>`<i style="height:${h}%"></i>`).join("")}</div><button data-toast="${r[1]} report opened.">Open report →</button></article>`).join("")}</div></div>`; }

function settingsPage(){ const integrations=[["GHL","GoHighLevel","Available"],["S","Stripe","Not connected"],["T","Twilio","Not connected"],["G","Google Calendar","Available"],["TX","Tax Preparation Software","Demo"],["DS","Secure Document Storage","Demo"]]; return `<div class="page">${heading("OFFICE CONFIGURATION","Settings","Shape the command center around your team, brand, and workflow.",'<button class="button secondary" id="resetDemo">Reset demo data</button><button class="button primary" data-toast="Settings saved in demo mode.">Save changes</button>')}<div class="settings-layout"><aside>${["Office Profile","Branding","Workflow Stages","Team Permissions","Notifications","Templates","Payment Settings","Integrations"].map((x,i)=>`<button class="${i===7?"active":""}">${x}</button>`).join("")}</aside><main><p class="eyebrow">CONNECTED SERVICES</p><h2>Integrations</h2><p>These cards are placeholders and do not create real connections.</p><div class="integration-grid">${integrations.map(x=>`<article><span>${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div><button data-toast="${x[1]} is unavailable in this demo.">${x[2]==="Available"?"Connect":"Manage"}</button></article>`).join("")}</div></main></div></div>`; }

function renderView(){
  const views={dashboard,workflow,clients:clientsPage,forms:formsPage,portal:portalPage,communications:communicationsPage,documents:documentsPage,payments:paymentsPage,team:teamPage,reports:reportsPage,settings:settingsPage};
  $("#appContent").innerHTML=views[currentView](); bindViewEvents();
}

function bindViewEvents(){
  $$('[data-add-client]').forEach(button=>button.addEventListener("click",openModal));
  [...$("#appContent").querySelectorAll('[data-view]')].forEach(button=>button.addEventListener("click",()=>navigate(button.dataset.view)));
  $$('[data-toast]').forEach(button=>button.addEventListener("click",()=>toast(button.dataset.toast)));
  $$('[data-export]').forEach(button=>button.addEventListener("click",()=>exportCsv(button.dataset.export)));
  $$('[data-client-id]').forEach(element=>element.addEventListener("click",()=>openClient(Number(element.dataset.clientId))));
  $$('[data-client-name]').forEach(element=>element.addEventListener("click",()=>openClient(clients.find(c=>c.name===element.dataset.clientName)?.id)));
  $$('[data-mode]').forEach(button=>button.addEventListener("click",()=>{workflowMode=button.dataset.mode;renderView()}));
  const workflowSearch=$("#workflowSearch"); if(workflowSearch) workflowSearch.addEventListener("input",e=>{const list=clients.filter(c=>`${c.name} ${c.type}`.toLowerCase().includes(e.target.value.toLowerCase()));$("#workflowArea").innerHTML=workflowMode==="board"?kanban(list):clientTable(list);bindWorkflowCards()});
  const clientSearch=$("#clientSearch"); if(clientSearch) clientSearch.addEventListener("input",e=>{$("#clientTableWrap").innerHTML=clientTable(clients.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(e.target.value.toLowerCase())));bindWorkflowCards()});
  bindWorkflowCards();
  $$('[data-thread]').forEach(button=>button.addEventListener("click",()=>{activeThread=Number(button.dataset.thread);renderView()}));
  $("#sendMessage")?.addEventListener("click",()=>{if($("#messageText").value.trim()){toast("Message added to the demo conversation—not sent.");$("#messageText").value=""}});
  $("#resetDemo")?.addEventListener("click",()=>{if(confirm("Reset all locally saved demo changes?")){clients=cloneDefaults();saveClients();toast("Demo data restored.");renderView()}});
}
function bindWorkflowCards(){
  $$('[data-client-id]').forEach(element=>{element.onclick=()=>openClient(Number(element.dataset.clientId));element.ondragstart=e=>e.dataTransfer.setData("clientId",element.dataset.clientId)});
  $$('.kanban-column').forEach(column=>{column.ondragover=e=>e.preventDefault();column.ondrop=e=>{e.preventDefault();const id=Number(e.dataTransfer.getData("clientId"));const client=clients.find(c=>c.id===id);if(client){client.stage=column.dataset.stage;client.activity="Just now";saveClients();renderView();toast(`${client.name} moved to ${stageLabel(client.stage)}.`)}}});
}

function openClient(id){ const c=clients.find(client=>client.id===id); if(!c)return; $("#clientDrawer").innerHTML=`<div class="drawer-head"><div class="avatar gold">${initials(c.name)}</div><div><p class="eyebrow">CLIENT RECORD</p><h2>${escapeHtml(c.name)}</h2><small>${escapeHtml(c.type)}</small></div><button id="closeDrawer">×</button></div><div class="drawer-body"><p class="eyebrow">CURRENT STAGE</p><h3>${stageLabel(c.stage)}</h3><div class="detail-grid"><span>Email<strong>${escapeHtml(c.email)}</strong></span><span>Phone<strong>${escapeHtml(c.phone)}</strong></span><span>Assigned to<strong>${escapeHtml(c.assignee)}</strong></span><span>Balance<strong>${c.balance?`$${c.balance}.00`:"Paid"}</strong></span></div><div class="timeline"><div><strong>Client record reviewed</strong><small>Today · Office administrator</small></div><div><strong>Workflow status: ${stageLabel(c.stage)}</strong><small>${c.activity}</small></div><div><strong>${escapeHtml(c.tags[0])}</strong><small>Client file note</small></div></div></div><div class="drawer-actions"><button class="button secondary" data-toast="Follow-up task added in demo mode.">＋ Add task</button><button class="button primary" data-toast="Message composer opened.">✉ Message client</button></div>`; $("#clientOverlay").classList.add("open"); $("#clientDrawer").classList.add("open"); $("#closeDrawer").onclick=closeDrawer; $("#clientOverlay").onclick=closeDrawer; $("#clientDrawer").querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast)); }
function closeDrawer(){ $("#clientOverlay").classList.remove("open"); $("#clientDrawer").classList.remove("open"); }
function openModal(){ $("#modalOverlay").classList.add("open"); }
function closeModal(){ $("#modalOverlay").classList.remove("open"); $("#clientForm").reset(); }

function exportCsv(kind){ let content,name;if(kind==="clients"){content=["Name,Email,Phone,Return Type,Stage,Assigned To,Balance",...clients.map(c=>[c.name,c.email,c.phone,c.type,stageLabel(c.stage),c.assignee,c.balance].map(v=>`"${v}"`).join(","))].join("\n");name="solutions-tax-pro-clients.csv"}else if(kind==="payments"){content="Client,Amount,Status,Date\n"+payments.map(r=>r.join(",")).join("\n");name="stp-transactions.csv"}else{content="Metric,Value\nRevenue Collected,$84620\nActive Clients,184\nReturns In Progress,126\nNeeds Attention,12";name="stp-command-center-report.csv"}const url=URL.createObjectURL(new Blob([content],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);toast("CSV report downloaded.")}

function initializeApp(){
  if(appInitialized) return;
  appInitialized = true;
  $("#sideNav").addEventListener("click",e=>{const button=e.target.closest("[data-view]");if(button)navigate(button.dataset.view)});
  $("#menuButton").onclick=()=>{$("#sidebar").classList.toggle("open");$("#sidebarScrim").classList.toggle("open")};
  $("#sidebarScrim").onclick=()=>{$("#sidebar").classList.remove("open");$("#sidebarScrim").classList.remove("open")};
  $("#loginForm").onsubmit=e=>{e.preventDefault();$("#loginScreen").classList.add("dismissed")};
  $("#viewDemo").onclick=()=>$("#loginScreen").classList.add("dismissed");
  $("#showPassword").onclick=()=>{const input=$("#passwordInput");input.type=input.type==="password"?"text":"password";$("#showPassword").textContent=input.type==="password"?"Show":"Hide"};
  $("#closeModal").onclick=closeModal;
  $("#modalOverlay").onclick=e=>{if(e.target===$("#modalOverlay"))closeModal()};
  $("#clientForm").onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);const client={id:Date.now(),name:data.get("name"),email:data.get("email"),phone:data.get("phone"),type:data.get("type"),stage:data.get("stage"),assignee:data.get("assignee"),balance:Number(data.get("balance")||0),activity:"Just now",tags:["New"]};clients.unshift(client);saveClients();closeModal();renderView();toast(`${client.name} added to Client Workflow.`)};
  $("#globalSearch").onkeydown=e=>{if(e.key!=="Enter")return;const query=e.target.value.toLowerCase().trim();const match=clients.find(c=>c.name.toLowerCase().includes(query)||c.phone.includes(query));match?openClient(match.id):toast("No matching demo client found.")};
  $("#stageSelect").innerHTML=stages.map(([id,label])=>`<option value="${id}">${label}</option>`).join("");
  renderNav();
  renderView();
}

if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",initializeApp,{once:true});
else initializeApp();
